name: Pokemon Vue 3

on:
    # Runs on pushes targeting the default branch
    push:
        branches: [ "main" ]

jobs:
    # Job 1: build & test
    build-and-test:
        name: Deploy Pokemon Vue 3
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v4
                with:
                    node-version: '21.x'
                    cache: 'npm'

            -   name: Install dependencies & Build Vue 3
                run: |
                    npm ci
                    export NODE_OPTIONS="--max_old_space_size=4096"
                    npm run build
                env:
                    VITE_APP_ROOT_API: ${{ secrets.VITE_APP_ROOT_API }}

            -   name: Copy file to VPS
                uses: appleboy/scp-action@master  # Use the latest version
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    passphrase: ${{ secrets.SSH_PASSPHRASE }}
                    #port: ${{ secrets.PORT }} #port of server - often port is 22
                    source: "ecosystem.config.cjs"
                    target: "/var/www/vue-pokemon"

            -   name: Copy folder to VPS
                uses: appleboy/scp-action@master  # Use the latest version
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    passphrase: ${{ secrets.SSH_PASSPHRASE }}
                    #port: ${{ secrets.PORT }} #port of server - often port is 22
                    source: "./dist"
                    target: "/var/www/vue-pokemon"

            -   name: Configure SSH agent and Restart PM2
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    passphrase: ${{ secrets.SSH_PASSPHRASE }}
                    script: |
                        cd /var/www/vue-pokemon
                        pm2 startOrRestart ecosystem.config.cjs --env production
